package applier

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/waf-agent/internal/config"
)

type ModsecApplier struct {
	cfg *config.Config
}

func NewModsecApplier(cfg *config.Config) *ModsecApplier {
	return &ModsecApplier{cfg: cfg}
}

func (a *ModsecApplier) Apply(ctx context.Context, domain string, payload []byte) error {
	if domain == "" || domain == "default" {
		domain = extractModsecDomain(payload)
	}
	if domain == "" {
		return fmt.Errorf("could not determine domain from modsec config")
	}

	slog.Info("applying modsec config", "domain", domain)

	cfgPath := filepath.Join(a.cfg.Nginx.ModsecDir, domain+".conf")

	// Backup
	if a.cfg.Nginx.BackupEnabled {
		if data, err := os.ReadFile(cfgPath); err == nil {
			bakPath := cfgPath + ".bak"
			if err := os.WriteFile(bakPath, data, 0644); err != nil {
				slog.Warn("backup modsec config failed", "path", bakPath, "error", err)
			}
		}
	}

	// Atomic write
	tmpPath := cfgPath + ".tmp"
	if err := os.WriteFile(tmpPath, payload, 0644); err != nil {
		return fmt.Errorf("write modsec config: %w", err)
	}
	if err := os.Rename(tmpPath, cfgPath); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("rename modsec config: %w", err)
	}

	return nil
}

func extractModsecDomain(payload []byte) string {
	content := string(payload)
	// Extract from comment: "# Generated by waf-control for policy: {name}"
	for _, line := range strings.Split(content, "\n") {
		if strings.Contains(line, "Generated by waf-control") {
			if idx := strings.LastIndex(line, ":"); idx >= 0 {
				name := strings.TrimSpace(line[idx+1:])
				return name
			}
		}
	}
	return "unknown"
}
